"""
Prometheus metrics collectors for LedgerGPT pipeline components.
"""
from prometheus_client import Counter, Gauge, Histogram, Summary

# ── Ingestion metrics ────────────────────────────────────────────────────────
TWEETS_INGESTED = Counter(
    "ledgergpt_tweets_ingested_total",
    "Total tweets ingested",
)
REDDIT_POSTS_INGESTED = Counter(
    "ledgergpt_reddit_posts_total",
    "Total Reddit posts ingested",
)
NEWS_ARTICLES_INGESTED = Counter(
    "ledgergpt_news_articles_total",
    "Total news articles ingested",
    ["source"],
)

# ── LLM metrics ──────────────────────────────────────────────────────────────
LLM_INFERENCE_LATENCY = Histogram(
    "ledgergpt_llm_inference_seconds",
    "FinLLaMA inference latency",
    ["task"],
    buckets=[0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 30.0],
)
LLM_TOKENS_GENERATED = Counter(
    "ledgergpt_llm_tokens_total",
    "Total tokens generated by FinLLaMA",
)
SENTIMENT_DISTRIBUTION = Counter(
    "ledgergpt_sentiment_labels_total",
    "Sentiment label distribution",
    ["sentiment", "source"],
)

# ── Signal metrics ───────────────────────────────────────────────────────────
SIGNALS_GENERATED = Counter(
    "ledgergpt_signals_generated_total",
    "Trading signals generated",
    ["ticker", "signal"],
)
SIGNAL_CONFIDENCE = Histogram(
    "ledgergpt_signal_confidence",
    "Signal confidence distribution",
    ["signal"],
    buckets=[0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95, 1.0],
)

# ── Execution metrics ────────────────────────────────────────────────────────
ORDERS_PLACED = Counter(
    "ledgergpt_orders_placed_total",
    "Broker orders placed",
    ["ticker", "side"],
)
ORDER_VALUE_USD = Summary(
    "ledgergpt_order_value_usd",
    "USD value of placed orders",
)
POSITION_PNL = Gauge(
    "ledgergpt_position_pnl_usd",
    "Unrealised PnL per ticker",
    ["ticker"],
)

# ── System metrics ───────────────────────────────────────────────────────────
KAFKA_LAG = Gauge(
    "ledgergpt_kafka_consumer_lag",
    "Kafka consumer lag per topic",
    ["topic"],
)
MODEL_LAST_TRAINED = Gauge(
    "ledgergpt_model_last_trained_timestamp",
    "Unix timestamp of last model training run",
)


class MetricsCollector:
    """Helper class to record metrics from various pipeline stages."""

    @staticmethod
    def record_sentiment(sentiment: str, source: str, confidence: float) -> None:
        SENTIMENT_DISTRIBUTION.labels(sentiment=sentiment, source=source).inc()

    @staticmethod
    def record_signal(ticker: str, signal: str, confidence: float) -> None:
        SIGNALS_GENERATED.labels(ticker=ticker, signal=signal).inc()
        SIGNAL_CONFIDENCE.labels(signal=signal).observe(confidence)

    @staticmethod
    def record_order(ticker: str, side: str, value_usd: float) -> None:
        ORDERS_PLACED.labels(ticker=ticker, side=side).inc()
        ORDER_VALUE_USD.observe(value_usd)

    @staticmethod
    def update_position_pnl(ticker: str, pnl: float) -> None:
        POSITION_PNL.labels(ticker=ticker).set(pnl)

    @staticmethod
    def record_llm_latency(task: str, latency_sec: float) -> None:
        LLM_INFERENCE_LATENCY.labels(task=task).observe(latency_sec)
